sudo: required
dist: trusty
before_install:
  - sudo apt-get update
  - sudo apt-get -qq install libcppunit-dev
  - sudo apt-get -qq install cmake
  - sudo apt-get -qq install qtbase5-dev
  - sudo apt-get -qq install astyle
script:
  - ./.formatter-check.sh
  - ./.build.sh
notifications:
  slack: kronosus:1qazkyb5u4Kx7Rtqlk8IB83b
cache:
  directories:
    - bin
