language: cpp
sudo: false
compiler:
  - gcc
os:
  - linux
addons:
  apt:
    sources:
      # For cmake >= 2.8.8
      - kubuntu-backports
    packages:
      - qt5-default
      - libqt5-dev
      - libcppunit-dev
      - cmake
      - astyle
notifications:
  slack: kronosus:1qazkyb5u4Kx7Rtqlk8IB83b
cache:
  directories:
    - bin
script:
  - ./.formatter-check.sh
  - ./.build.sh
