sudo: required
dist: trusty
before_install:
  - sudo apt-get update
  - sudo apt-get -qq install libcppunit-dev
  - sudo apt-get -qq install cmake
  - sudo apt-get -qq install qtbase5-dev
  
  # build astyle because the astyle version in the official repos is outdated
  - cd ../..
  - wget http://sourceforge.net/code-snapshots/svn/a/as/astyle/code/astyle-code-486-tags-2.05.1.zip && unzip astyle-code-486-tags-2.05.1.zip && cd astyle-code-486-tags-2.05.1 
  - cd AStyle/build/gcc
  - make release
  - sudo make install
  - cd ../../../../quappi/STUPRO
  
script:
  - ./.formatter-check.sh
  - ./.build.sh
notifications:
  slack: kronosus:1qazkyb5u4Kx7Rtqlk8IB83b
cache:
  directories:
    - bin
