sudo: required
dist: trusty
before_install:
  - sudo apt-get update
  - sudo apt-get -qq install libcppunit-dev
  - sudo apt-get -qq install cmake
  - sudo apt-get -qq install qtbase5-dev
#  - sudo apt-get -qq install astyle
  - wget http://sourceforge.net/code-snapshots/svn/a/as/astyle/code/astyle-code-486-tags-2.05.1.zip && unzip astyle-code-489-tags-2.05.1.zip && cd astyle-code-486-tags-2.05.1 
  - cd AStyle/build/gcc && sudo make install
script:
  - ./.formatter-check.sh
  - ./.build.sh
notifications:
  slack: kronosus:1qazkyb5u4Kx7Rtqlk8IB83b
cache:
  directories:
    - bin
