language: cpp
sudo: false
compiler:
  - gcc
os:
  - linux
addons:
  apt:
    sources:
      # For cmake >= 2.8.8
      - kubuntu-backports
    packages:
      - libqt4-dev
      - qt4-dev-tools
      - cmake
      - astyle
notifications:
  slack: kronosus:1qazkyb5u4Kx7Rtqlk8IB83b
cache:
  directories:
    - bin
script:
  - ./.formatter-check.sh
  - ./.configure.sh
  - cd bin && make
  - cd bin && make test
